### ISSUE TITLE
An update?

### ISSUE THREAD

**Issue by tmpm697** [ggVGc/vim-fuzzysearch#2]
Do you have time to give this an update, I use it daily basis. When I profile function vim, this plugin take sometime to execute.

**Comment by ggVGc** [comment]
Hey, glad someone else is using it!
I am not sure it could be optimized much in the current implementation, since it's basically all vim regex.
The regexes will always be quite expensive compared to normal search, since the whole point is having lots of wildcards.
Do you have an example text and search input that produces very slow behaviour?

**Comment by tmpm697** [comment]
I think regrex slow down a bit but acceptable for me currently. thanks.
